### ISSUE TITLE
Error when running script

### ISSUE THREAD

**Issue by brak265** [lulle2007200/SwitchSDSetup#10]
Hi, I am receiving the following error when running the script, despite /StartFiles/HOSStockStartFiles.zip being in the correct location along with the other files mentioned:

31457280 bytes (31 MB, 30 MiB) copied, 8 s, 3.9 MB/s 
30+0 records in
30+0 records out
31457280 bytes (31 MB, 30 MiB) copied, 8.10458 s, 3.9 MB/s
0+0 records in
0+0 records out
0 bytes copied, 0.000190869 s, 0.0 kB/s
0+0 records in
0+0 records out
0 bytes copied, 8.0995e-05 s, 0.0 kB/s
unzip:  cannot find or open ./StartFiles/HOSStockStartFiles.zip, ./StartFiles/HOSStockStartFiles.zip.zip or ./StartFiles/HOSStockStartFiles.zip.ZIP.
unzip:  cannot find or open ./StartFiles/Hekate.zip, ./StartFiles/Hekate.zip.zip or ./StartFiles/Hekate.zip.ZIP.
umount: /dev/sdb: not mounted.
umount: /dev/sdb1: not mounted.
umount: /dev/sdb2: not mounted.
umount: /dev/sdb3: not mounted.
umount: /dev/sdb4: not mounted.
umount: /dev/sdb5: not mounted.
umount: /dev/sdb6: not mounted.
umount: /dev/sdb7: not mounted.
umount: /dev/sdb8: not mounted.
Done

**Comment by lulle2007200** [comment]
Make sure to run the script from the same directory (cd /path/to/script/folder)
