### ISSUE TITLE
Supported SXOS?

### ISSUE THREAD

**Issue by rpf16rj** [lulle2007200/SwitchSDSetup#15]
Hi, i have backup of my emunand created whit SXOS payload. I used your script and not work. The boot on SXOS using sysnand. The emunand is ignored. 

In search in web, i see a post of forum what say waht SXOS default partidion of emunand is the partition 2 of SD.  I try change order of create partition in the script, but not working aganin.

Any idea?

**Comment by lulle2007200** [comment]
I dont use sxos, i dont know how they set up emummc, therefore my interest to get it working with sxos is rather limited to say the least. On top of that, i cant test with sxos since i dont own it.
