### ISSUE TITLE
Add support for emuMMC partitions with variable sizes.

### ISSUE THREAD

**Issue by DarkMatterCore** [lulle2007200/SwitchSDSetup#5]
Extra useful if you're using an emuMMC with a resized USER partition, generated by tools such as [NxNandManager](https://github.com/eliboa/NxNandManager) or [resize-user.py](https://gist.github.com/ckurtz22/5748f3f761e0a546675f2720a1e5e486).

Personally, I brought my emuMMC USER partition down to 2 GiB, so a lot of SD card space is wasted  by the script by using a hardcoded emuMMC partition size.

Maybe asking the user about their emuMMC size could do the trick. Another option would be making the script capable of flashing the emuMMC image itself after creating the SD card partition (no need to ask the user for the emuMMC image size if they provide it).

**Comment by lulle2007200** [comment]
I can allow shrinking for the emummc partition and add a warning or something.
I can also add an option to flash an mmc image, assuming the user provides one, didnt do that yet since hekates emummc manager is convenient enough, for me atleast.

**Comment by DarkMatterCore** [comment]
Sounds good to me. :)

I can help you test any changes if you need it.
