### ISSUE TITLE
Reserve space for hidden emuMMC images.

### ISSUE THREAD

**Issue by DarkMatterCore** [lulle2007200/SwitchSDSetup#6]
It is also possible to reserve space for the emuMMC image in the SD card without actually creating a logical partition for it, and then flash it using dd or other custom tools. Much like 3DS emuNANDs used to work some years ago.

This way, there will be no need to use MBR fixes nor a custom driver to hide the emuMMC partition under Windows. There will be no logical partition at all to begin with.

Updating the emummc.ini file to point to the start sector from the emuMMC is a pretty trivial task. The resulting emuMMC image works fine with both fusee-primary.bin and Hekate + FSS0.

**Comment by lulle2007200** [comment]
I could add an (advanced) option for that. 
Downside is that hekate doesnt see the partition then, which makes things a little less convenient.

**Comment by DarkMatterCore** [comment]
Yeah, a feature like this is probably only intended for experienced users. So adding an "advanced" disclaimer if you ever implement it sounds right.

Hekate is capable of detecting a hidden emuMMC image and won't refuse to boot it. But since it relies on an actual logical partition for it being available, any backup/restore option won't work.

This is no problem at all, though. If you ever need to backup/restore the hidden emuMMC, you can do that by yourself using dd.

**Comment by lulle2007200** [comment]
By the way, the filter driver may still be needed for windows since it can happen that it uses gpt instead of the mbr by default (which would still mess things up badly).
On some Windows machines it just works as intended without any additional drivers (e.g. just mounts the hos_data partition with the other partitions being hidden).

i added the option to call the script with --emummc [hidden] [new default size in mb] [path/to/emummc.img]
to not add it to mbr, set a custom default size and provide an mmc image to be flashed.
Keep in mind, that running the --fix-mbr option will add the emummc partition to mbr again and if the image is bigger than the default size, it will set the default size to the size of the image.

Will push changes in like 30min

**Comment by DarkMatterCore** [comment]
It would be nice to make the script retrieve the size from the provided eMMC image and use that to automatically determine the reserved area size.

I think both arguments could be mutually exclusive. For example:

`--emummc [hidden] [path/to/emummc.img]` retrieves the image size and uses that to know how big the reserved area should be. The retrieved size would probably have to be aligned to 1 MiB.

`--emummc [hidden] [new default size in mb]` generates a reserved area using the user-provided size without flashing any image at all.

**Comment by lulle2007200** [comment]
didnt mention that, any of the arguments are optional. In case you provide both, image and size, it will use either the size of the image or the size you provided, depending on which is larger.

**Comment by DarkMatterCore** [comment]
Excellent! Sounds great. :)

**Comment by lulle2007200** [comment]
alright, pushed changes. If you want to test, download setup.sh and replace the one from releases.
Couldnt test yet but should work technically.
e.g. ./setup.sh  --emummc hidden 30000 /home/xyz/emummc.img
(img name must match emummc.img)

**Comment by DarkMatterCore** [comment]
Will do. I will report back as soon as I finish my tests.

**Comment by DarkMatterCore** [comment]
https://github.com/lulle2007200/SwitchSDSetup/blob/6e182623c083fce1237eb1725b3195dbe04b14d7/setup.sh#L875-L880

I believe the call to `mkfs.vfat` should actually be part of the conditional block. There's no real need to create a filesystem for hidden emuMMC images, even more so if it will get overwritten right away if the user provides an emuMMC image.

Also, wouldn't the condition itself actually have be something like this?
```
If [[ -z $Emummc_hidden ]] || [[ "$Emummc_hidden" -ne 1 ]]
```
Right now, it seems like the MBR partition creation will actually run if the `hidden` keyword is provided as part of the command.

**Comment by lulle2007200** [comment]
I guess the mkfs call could be part of conditional block. Yeah, if condition should just be [[ -z $Emummc_hidden ]], forgot to change that.
