### ISSUE TITLE
Wrong line endings, typo in if statement, file test condition failing

### ISSUE THREAD

**Issue by qwertycody** [lulle2007200/SwitchSDSetup#7]
setup.sh, when unzipping directly after a wget from releases the end of line conversion needs to be set for unix, not really a issue as easily fixed.

Line 875 - If Typo, needs to be lowercase if
![image](https://user-images.githubusercontent.com/4968312/83904933-c7c2fb80-a72e-11ea-84eb-898572838fda.png)

Line 165 - Tegra File Test Condition Failing Despite Having Files in Directories Required
![image](https://user-images.githubusercontent.com/4968312/83905037-f2ad4f80-a72e-11ea-92a5-21adc4f88b0e.png)

![image](https://user-images.githubusercontent.com/4968312/83905136-28eacf00-a72f-11ea-9ec4-503a34f0968d.png)

**Comment by lulle2007200** [comment]
What file path did you pass to the script?

**Comment by lulle2007200** [comment]
As for the line endings, not really sure how that happened. Saved with unix line endings, also worked fine when i tested it. Will fix tomorrow.

**Comment by qwertycody** [comment]
I need to retest the conditions for file detection. Pretty sure I didn't have the system.img at the time so will let you know Monday probably.

**Comment by lulle2007200** [comment]
Makes sense it fails in that case. In case it fails again, even with system.img in place, try passing the full path (e.g. without '~', that causes problems sometimes for various reasons, i didnt bother to fix that yet)

**Comment by qwertycody** [comment]
Test condition succeeded. It was the system.img.

The issue with the wrong casing on the if statement and the EOL Conversion still persist but those are super minor.
