### ISSUE TITLE
When No Partitions Test Condition Fails - AKA blank disk with 0 partitions

### ISSUE THREAD

**Issue by qwertycody** [lulle2007200/SwitchSDSetup#8]
![image](https://user-images.githubusercontent.com/4968312/83910829-373de880-a739-11ea-9107-585d69a44fa4.png)

![image](https://user-images.githubusercontent.com/4968312/83910881-4a50b880-a739-11ea-83da-0319718af217.png)

**Comment by lulle2007200** [comment]
I'm kind of surprised, nobody reported this yet. Will add a blank disk check.
