### ISSUE TITLE
script fails on device selection

### ISSUE THREAD

**Issue by accidental-expert** [lulle2007200/SwitchSDSetup#9]
``./setup.sh: line 876: syntax error near unexpected token `then'``
``./setup.sh: line 876: `			then'``

after choosing a device. can't continue from here. this is also after converting the setup.sh file to unix format in vi and other methods. using Ubuntu 20.04 LTS live on a usb stick.

**Comment by lulle2007200** [comment]
Apparently there is a typo in line 875. "If" has to be "if".
Probably duplicate of #7
